[package]
name = "rain-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
serenity.workspace = true
appflow.workspace = true
log.workspace = true
logger.workspace = true
lazy_static.workspace = true
thiserror.workspace = true
common = { path = "../common" }
database = { path = "../database" }
material = { path = "../material" }
