begin;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS title INT DEFAULT 0;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS gold INT DEFAULT 0;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS silver INT DEFAULT 0;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS bronze INT DEFAULT 0;
end;
