on:
  workflow_dispatch: {}
  push:
    branches:
      - senpai

name: Documentation

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: vite-press/package-lock.json


      - run: cd ./vite-press && npm install --frozen-lockfile

      - name: Build
        run: cd ./vite-press && npm run docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: vite-press/docs/.vitepress/dist 
