name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  upload-artifact:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: build release
        run: cargo build --release
      - name: rename windows config and move exutable
        if: matrix.platform == 'windows-latest'
        run: ren ./config.json.example config.json&&copy ./target/release/rain-bot.exe .&&mkdir save&&cd save&&echo. >save_folder.txt&&dir


      - name: rename linux and mac config and move exutable
        if: matrix.platform != 'windows-latest'
        run: mv ./config.json.example config.json&&cp ./target/release/rain-bot .&&mkdir save&&touch ./save/this_is_save_folder.txt


      - name: upload windows-artefact
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'windows-latest'
        with:
          name: windows-artifact
          path: |
            rain-bot.exe
            src/
            icon/
            save/
            query/
            Cargo.toml
            config.json

      - name: upload linux-artifact
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'ubuntu-20.04'
        with:
          name: linux-artifact
          path: |
            rain-bot
            src/
            icon/
            save/
            query/
            Cargo.toml
            config.json

      - name: upload macos-artifact
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'macos-latest'
        with:
          name: mac-artifact
          path: |
            rain-bot
            src/
            icon/
            save/
            query/
            Cargo.toml
            config.json
