name: 'publish'
on:
  push:
    branches:
      - sensei
jobs:
  upload-artifact:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: set env
        run: export SQLX_OFFLINE=true
      - name: build release
        run: cargo build --release --bins -Z unstable-options --artifact-dir artefact
      - name: upload artefact
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'windows-latest'
        with:
          name: matrix.platform
          path: |
            artefact/
